"""create propiedades table

Revision ID: 5a18bb874c95
Revises: 
Create Date: 2026-09-26 13:50:14.375996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a18bb874c95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('propiedades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciudad', sa.Enum('CALI', 'MEDELLIN', 'BOGOTA', 'TULUA', name='ciudad_enum', native_enum=False, length=32), nullable=False),
    sa.Column('tipo_operacion', sa.Enum('VENTA', 'ARRIENDO', name='tipo_operacion_enum', native_enum=False, length=16), nullable=False),
    sa.Column('precio', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('habitaciones', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('barrio', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=120), nullable=False),
    sa.Column('fecha_extraccion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propiedades_barrio'), 'propiedades', ['barrio'], unique=False)
    op.create_index(op.f('ix_propiedades_ciudad'), 'propiedades', ['ciudad'], unique=False)
    op.create_index(op.f('ix_propiedades_precio'), 'propiedades', ['precio'], unique=False)
    op.create_index(op.f('ix_propiedades_tipo_operacion'), 'propiedades', ['tipo_operacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propiedades_tipo_operacion'), table_name='propiedades')
    op.drop_index(op.f('ix_propiedades_precio'), table_name='propiedades')
    op.drop_index(op.f('ix_propiedades_ciudad'), table_name='propiedades')
    op.drop_index(op.f('ix_propiedades_barrio'), table_name='propiedades')
    op.drop_table('propiedades')
    # ### end Alembic commands ###
