"""add property_type to propiedades

Revision ID: 833790859ef6
Revises: c874b66c1c05
Create Date: 2026-09-26 15:33:55.353368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833790859ef6'
down_revision: Union[str, None] = 'c874b66c1c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('property_type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_propiedades_property_type'), 'propiedades', ['property_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_propiedades_property_type'), table_name='propiedades')
    op.drop_column('propiedades', 'property_type')
    # ### end Alembic commands ###
