"""add url_original to propiedades

Revision ID: c874b66c1c05
Revises: 5a18bb874c95
Create Date: 2026-09-26 14:01:53.042598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c874b66c1c05'
down_revision: Union[str, None] = '5a18bb874c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propiedades', sa.Column('url_original', sa.String(length=1024), nullable=True))
    op.create_unique_constraint('uq_propiedades_url_original', 'propiedades', ['url_original'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_propiedades_url_original', 'propiedades', type_='unique')
    op.drop_column('propiedades', 'url_original')
    # ### end Alembic commands ###
